### ISSUE TITLE
.clap plugin support

### ISSUE THREAD

**Issue by RustoMCSpit** [SpotlightKid/ykchorus#5]

**Comment by SpotlightKid** [comment]
Fixed in 8b861715413b450d108546667a7b8424213086ba.

**Comment by RustoMCSpit** [comment]
wait what how did you do that so fast? what library are you using??

**Comment by SpotlightKid** [comment]
[DPF](https://github.com/DISTRHO/DPF)

This plugin was first created before CLAP existed or DPF had CLAP support. I "just" had to update DPF and adapt the makefiles.
