### ISSUE TITLE
  [Feature request] StudioRack integration

### ISSUE THREAD

**Issue by RustoMCSpit** [SpotlightKid/ykchorus#6]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by SpotlightKid** [comment]
Sorry, not doing that. While I appreciate the general effort to make plugin discovery and installation easier for end users, I don't think this is the right way.

Some reasons I dislike the proposed solution (not exhaustive):

* Requirement to clutter GitHub release names with "app store"-specific labels.
* Requirement to clutter project with "app store"-specific files.

I would much rather prefer a procedure, where the plugin registry is kept in a central repo and plugin authors can submit their plugins/releases via a Git PR or an API.

**Comment by RustoMCSpit** [comment]
> I would much rather prefer a procedure, where the plugin registry is kept in a central repo and plugin authors can submit their plugins/releases via a Git PR or an API.

this is being discussed to my knowledge and will be out in V2, you can join the DIscord and ask the dev themself and give input into how it should be done. I dont think it's an API, something about a yaml file i cant recall https://discord.gg/9D94f98PxP
